apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL : "https://github.com/Oumayma-Farhat/Terraform-project.git"
    targetRevision: HEAD
    path: terraform-project-time-printer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true